### ISSUE TITLE
❤️❤️❤️ Looking for Maintainers!!! ❤️❤️❤️

### ISSUE THREAD

**Issue by d6u** [react-container-query/react-container-query#75]
Hey, all.,

Thanks for all of your help and ❤️ to make this little library better. Now I think I don't qualify as a good maintainer of this repo because I no longer have time to work on this.

If someone can pick this up and move it forward, that will be deeply appreciated. I can make reasonable changes as long as it will help the users, e.g. create a org to host this etc. I will find a time to help you transition the ownership if necessary.

I will continue contributing my 2 cents along the way, but it won't be anything major. I will let this post sit here for a little while before move to next step, so  people can have time to respond.

Please comment below if you are interested. Thanks all!

**Comment by pixelbandito** [comment]
I'd like to help out. 
I see this is an ancient comment, but if it would still help you to just have another set of eyes to run tests and look at PRs, I'm down.

**Comment by pixelbandito** [comment]
As a gesture of good will 😄I submitted a PR just now. Hope you see it!

Side note - I like this library a lot, but if it's not really being maintained and there's a better, newer alternative, I'd love to hear about it.

I haven't found anything yet - maybe some other repo followers have?

**Comment by mdingena** [comment]
@pixelbandito you can follow me, I'll open-sourcing a solution within the next month or so.

**Comment by d6u** [comment]
Will close this for now. I have a bit more time recently and want to clean this up a little bit. Thanks for all the help!
